#!/bin/bash
dir=`dirname $(readlink -f $0)`
decoy="$dir/library/random.charge3.r3.mgf"
glyco="$dir/library/glyco_library.mgf"
msSLASH="$dir/msSLASH/bin/msSLASH"


echo $decoy
echo $glyco
while IFS= read -r line
do
	$msSLASH -l $glyco -d $decoy -e $line -o "$line".GlycoSLASH.tsv
done < $1

